version: '3'

services:
  artificial-intelligence:
    build: ./artificial-intelligence

  back-end:
    build: ./Back-end
    ports:
      - 8181:80
  
  front-end:
    build: ./Front-end
    ports:
      - 3000:3000